### ISSUE TITLE
[1.14.4] Random equipment given to the player on entering world/ logging in to server

### ISSUE THREAD

**Issue by Kamefrede** [p1ut0nium-git/Rough-Mobs-Revamped#14]
Forge Version: 28.2.1
Mod Version: 0.1.0

As titles says, when joining a singleplayer world or a server the player will get randomly given pieces of chainmail armor, a golden sword, or a stone sword.

**Comment by EternalShadow17** [comment]
yeah and on every respawn, it makes the mod kinda broken right now as you can easily dup armor

**Comment by p1ut0nium-git** [comment]
1.14.4 isn't ready for release. It's an alpha. I'll try to get it up to speed this week though.

**Comment by p1ut0nium-git** [comment]
Fixed as of version 0.1.2
