### ISSUE TITLE
conflict with Serene seasons

### ISSUE THREAD

**Issue by whattodrink** [p1ut0nium-git/Rough-Mobs-Revamped#19]
The random equipment error was fixed . but there is a new error . it seems can't work with Serene Seasons mod.I don't konw why a mob mod will be conflict with a environment mod.But the game will just stop in the creating world interface.please fix it.my english is bad.hope you can understand what i'm saying. : )

forge version:28.2.0
game version:1.14.4

**Comment by whattodrink** [comment]
[debug.log](https://github.com/p1ut0nium-git/Rough-Mobs-Revamped/files/4323345/debug.log)

**Comment by p1ut0nium-git** [comment]
I've found the bug and fixed it. I will upload the working version sometime tonight after I track down another bug.

**Comment by p1ut0nium-git** [comment]
Fixed in version 0.1.3 
https://www.curseforge.com/minecraft/mc-mods/rough-mobs-revamped/files/2899718
