### ISSUE TITLE
Weapon switch stall

### ISSUE THREAD

**Issue by Ghoul-Generator** [p1ut0nium-git/Rough-Mobs-Revamped#2]
Hi, Previously when Rough mobs was closed source, an issue was identified which was at first assumed to be a compat issue with dynamic stealth and the following issue was created there: https://github.com/Laike-Endaril/Dynamic-Stealth/issues/51
However, it was deduced that this was a bug in rough mob's implementation of weapon switching and Endaril resolved the compat by simply overriding the AI behavior. Now that Rough mobs is being updated again, is it possible for you to roll those changes directly into the mod? Rather, I know the changes made by Endaril in his compat take into account his own mod, however the other changes relating to the A.I task seem to apply in general as I've noticed this weapon switch bug present even without dynamic stealth present.

**Comment by p1ut0nium-git** [comment]
I'll have a look.

**Comment by p1ut0nium-git** [comment]
Fixed. See version 2.3.8
