### ISSUE TITLE
Bosses crashing server

### ISSUE THREAD

**Issue by issueboi** [p1ut0nium-git/Rough-Mobs-Revamped#20]
Hi,

I really like how the mod improved since RM 2 but for some reason bosses are crashing my server.
Worst thing is that even though I set their spawn chance to 0 they still do and crash the server afterwards.

If that helps with anything, it doesn't matter if it's a zombie boss or a skeletone one, both are causing a shutdown, also it happened every time and in multiple locations.

Basically, it's crashing no matter the circumstances, if there is a boss there will be a crash.

Here is a crash report: https://pastebin.com/w5r7Jv2M

At the very least, could you tell me what to do to not let them spawn since both:

zombie_BossChance=0 
skeleton_BossChance=0

are already set this way and it didn't help?

**Comment by p1ut0nium-git** [comment]
Thanks for the crash report, but I've checked the code and debugged. I am not getting that crash on my end. I can also control spawn rates for bosses. Setting to zombie bosses to 0 they no longer spawn. I've tried on an actual multiplayer server with two players. No crash. It could be some sort of mod compatibility issue. Can you try running rough mobs by itself on a test server and see if you have the same issue?

**Comment by p1ut0nium-git** [comment]
Actually, I have discovered that the type of For each loop I'm using may cause crashes related to the error you are getting (Concurrent Modification). I'm investigating changing the for loop into an iterator and I'll see if that works. If it does, I'll upload a new version today and you can try that one.

**Comment by p1ut0nium-git** [comment]
Hopefully this is fixed in version 2.3.14 https://www.curseforge.com/minecraft/mc-mods/rough-mobs-revamped/files/2904076
