### ISSUE TITLE
Explosion on Death Destroys Item Drops

### ISSUE THREAD

**Issue by SandwichHorror** [p1ut0nium-git/Rough-Mobs-Revamped#21]
By default, the blaze's "death explosion" feature and any other entity that's added to the blaze features list causes that mob's drops to be destroyed instantly about 9/10 times, at least when the value exceeds 0.5. (Mine is at 1.3).

Is there a way to prevent this death explosion from destroying drops from the slain mob? It makes gathering blaze rods extremely tedious, and simply setting the explosion to a much lower value would defeat the purpose of being able to adjust the explosion strength in the first place.

If this isn't possible, I would love to find a mod that sets certain items to be completely immune to explosions - I tried and could not find any. 

Thanks!

**Comment by p1ut0nium-git** [comment]
Thanks for the report. I’ll investigate.

**Comment by p1ut0nium-git** [comment]
Fixed

1.12.2 - version 2.3.16
1.14.4 - version 0.1.5
