### ISSUE TITLE
Not successfully breaking blocks

### ISSUE THREAD

**Issue by Casiopeax** [p1ut0nium-git/Rough-Mobs-Revamped#32]
Last version of 1.14.4 (roughmobsrevamped-1.14.4-0.1.5)

When breaking any block it looks like I have removed it, but it actually still there, won't let me pass through the place i removed the block, and will appear again when starting the world again. (Of course it also won't drop).
Only happens in survival though, and it's the mod alone.

Because of broken english and kid kind of explanatory i will leave a gif.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/63928840/79670626-75377b00-8192-11ea-8853-95c323f57e67.gif)

**Comment by p1ut0nium-git** [comment]
Should be fixed in 1.14.4-0.1.6 and 1.15.2-4.1.1
