### ISSUE TITLE
Feature request: Zombies (and/or other mobs) attack animals

### ISSUE THREAD

**Issue by RecursiveStar** [p1ut0nium-git/Rough-Mobs-Revamped#33]
I think it'd be cool if there was an ability to have Zombies, Zombie variants and/or other mobs, when not already targeting a player, villager, or iron golem, attack animals (chickens, pigs, cows, horses, mooshrooms, etc). It'd require the player to actively protect their livestock and stable and make zombies a more active threat, since they'd be frequently mobile.

**Comment by SandwichHorror** [comment]
You can do this yourself with the targetAttacker feature.

**Comment by RecursiveStar** [comment]
Thanks for the tip!
