### ISSUE TITLE
Feature request: Equip mobs with armor using dispensers

### ISSUE THREAD

**Issue by RecursiveStar** [p1ut0nium-git/Rough-Mobs-Revamped#34]
In vanilla Minecraft, certain mobs, according to the Minecraft Wiki, can be equipped with armor using dispensers: villagers, pillagers, vindicators, evokers, and witches.

Why not allow this functionality for all (or at least most) mobs?

**Comment by p1ut0nium-git** [comment]
Probably not going to do this. It is beyond the scope of this mod.
