### ISSUE TITLE
Feature Request: Mob Health Config Option

### ISSUE THREAD

**Issue by IRonicBruh** [p1ut0nium-git/Rough-Mobs-Revamped#36]
As title says..
Example:
- Creeper Health -
  Default Value 20, Range 1 - 999
Health Amount: 20

**Comment by SandwichHorror** [comment]
I don't understand. You can already set their health, add to it, reduce it, multiply it, whatever.

**Comment by IRonicBruh** [comment]
how? I must be blind.

**Comment by lamoyrl90** [comment]
config/roughmobsrevamped/attributes.toml

**Comment by p1ut0nium-git** [comment]
In version 1.12.2 it is found under attributes section. .maxHealth.
