### ISSUE TITLE
Bug: Boss Poison Fog is global, does not respect config

### ISSUE THREAD

**Issue by omnirusted** [p1ut0nium-git/Rough-Mobs-Revamped#42]
I have changed every value in the config, and it is all the same. Text warning stays on, cough always goes off, damage goes off every second or so, doing half a heart of damage, and is literally all over my world (or it might as well be). Bosses are spawning constantly, never dying, and do not die in the sunlight with a hat on (even though I made the config otherwise). Either there's a massive bug, or there needs to be a feature to turn bosses / fog off.

![unknown](https://user-images.githubusercontent.com/66576681/83983073-4ca14700-a8e0-11ea-9b8f-d17f18f1de3b.png)

**Comment by p1ut0nium-git** [comment]
Sorry I was on a long bneak from modding. It all works on my end, and no one else seems to have this issue. I'm closing this issue for now, but feel free to reopen if you still have trouble.
