### ISSUE TITLE
Issue running gradle runClient

### ISSUE THREAD

**Issue by laundry-96** [p1ut0nium-git/Rough-Mobs-Revamped#43]
Hey, I'm running into errors when attempting to load the dependent mods (SereneSeasons, Bookshelf, and GameStages)

Bookshelf: 
19:40:57] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: bookshelf, class net.darkhax.bookshelf.Bookshelf
java.lang.NoSuchMethodError: net.minecraft.util.NonNullList.func_191196_a()Lnet/minecraft/util/NonNullList;

GameStages: 
[19:40:57] [modloading-worker-3/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: gamestages, class net.darkhax.gamestages.GameStages
java.lang.NoSuchMethodError: net.minecraft.world.storage.loot.conditions.LootConditionManager.func_186639_a(Lnet/minecraft/world/storage/loot/conditions/ILootCondition$AbstractSerializer;)V

SereneSeasons: 
[19:40:57] [modloading-worker-2/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: sereneseasons, class sereneseasons.core.SereneSeasons
java.lang.NoSuchFieldError: field_180291_a

If you have any insight, or need anything from me, please let me know!

**Comment by p1ut0nium-git** [comment]
Sorry I was taking a long break from MC modding. I don't know why it won't work for you. It works for me. The build.gradle file contains the info you need for it to download those 3 mods. But make sure they exist in your Project and External Dependencies folder. You should see all three right at the top of this list. IF they aren't there then something is keeping you from getting them when you run. Not sure what that would be.

This is what the biuld.gradle file has:

```
repositories {
	maven { url 'https://maven.mcmoddev.com' }
	maven {
		name = "CurseForge"
        url = "https://minecraft.curseforge.com/api/maven/"
    }
}

dependencies {
	compile "net.darkhax.gamestages:GameStages-${minecraft_version}:${gameStages_version}"
	compile "net.darkhax.bookshelf:Bookshelf-${minecraft_version}:${bookshelf_version}"
	compile "serene-seasons:SereneSeasons-${minecraft_version}:${sereneSeasons_version}:universal"
}
```
