### ISSUE TITLE
zombie horses don't burn

### ISSUE THREAD

**Issue by or-n** [p1ut0nium-git/Rough-Mobs-Revamped#46]
They spawn without a raider and don't burn or despawn, despite changing the config. Also spawn rate is definitely too high.

**Comment by p1ut0nium-git** [comment]
Tested on my end and it works fine. Zombie horses do burn in daylight.

Control hostile horse burn during daylight in config:

```
    # Set this to false to prevent undead horses from burning in sunlight (as long as they have no rider) [default: true]
    B:hostileHorseBurn=true
```

Control zombie horse spawns here. Set to 0 to disable. Otherwise, the higher the value the less frequent they spawn.
    
```
    # Chance (1 in X) that a zombie spawns riding a zombie horse
    # Set to 0 to disable this feature [range: 0 ~ 32767, default: 10]
    I:zombieHorseChance=10
```
