### ISSUE TITLE
Wither Knockback May Be Dealing Damage to Player

### ISSUE THREAD

**Issue by TakoArishi** [p1ut0nium-git/Rough-Mobs-Revamped#48]
Modpack: Magiculture 2
Description: While using Terrasteel armor and a Terrasteel sword, any melee attack or melee-based projectile seems to cause the player to take damage from The Wither. The amount of damage seems to not be mitigated by any sort of defensive stats, but the knockback is mitigated by knockback resistance.

Comments: I'm not sure if the knockback change was meant to do this, but I've noticed that this Wither knockback change seems to deal damage to the player that attacks it. Every melee attack to the wither seems to deal about 2 hearts worth of damage, even from abilities like Botania's Terrasteel swords. (Amusingly enough, it even seems to activate off Roots' "Radiance" spell.)

From the little I've seen, I'm not sure if that Entity "attackEntityFrom" function call only does a knockback. Granted, I don't necessarily know how Minecraft methods work.

**Comment by TakoArishi** [comment]
Reproduced on Minecraft 1.12.2 with the following mods:
Forge Mod Loader 8.0.99.99
Minecraft Forge 14.23.5.2854
Baubles 1.12-1.5.2
JEI 4.15.0.297
Botania r1.10-363
Mouse Tweaks 2.10
Rough Mobs Revamped 1.12.2-2.3.17

**Comment by p1ut0nium-git** [comment]
Yes. This is intended. You can see from the second line below that it does 4 points of damage. I will add an option to disable this in the next update.

```
FeatureHelper.knockback(target, (EntityLivingBase) attacker, 1F, 0.05F);
attacker.attackEntityFrom(DamageSource.GENERIC, 4F);
```

**Comment by p1ut0nium-git** [comment]
Config option to enable/disable knockback damage added in version 2.3.19
