### ISSUE TITLE
If killed by Boss Poison Fog while playing with tomb many graves inventory gets deleted

### ISSUE THREAD

**Issue by Umpaa** [p1ut0nium-git/Rough-Mobs-Revamped#50]

**Comment by Aeron216** [comment]
Came here for the same issue, since not tombstone generates on Boss Poison death your inventory simply gets voided.

**Comment by Xenimus0** [comment]
same here, players dying from fog with no gravestone.

roughmobsrevamped-1.12.2-2.3.21

TombManyGraves-1.12-4.2.0

forge 2854

**Comment by BlitzProGaming** [comment]
Same issue that I'm having. Sucks to lose an inventory of gear to a bug.

roughmobsrevamped-1.12.2-2.3.21

TombManyGraves-1.12-4.2.0

Forge 1.12.2 14.23.5.2854

**Comment by p1ut0nium-git** [comment]
Fixed in 2.3.23
