### ISSUE TITLE
There is no bosses

### ISSUE THREAD

**Issue by ColaLiao** [p1ut0nium-git/Rough-Mobs-Revamped#53]
even i change the "zombie_BossChance=30",
there still no zombie boss,
and if change to  "zombie_BossChance=1",
there will no zombie spawn...

roughmobsrevamped-1.12.2-2.3.19.jar

**Comment by p1ut0nium-git** [comment]
zombie_BossChance=30 means there is a 1 out of every 30 zombies will be a boss
zombie_BossChance=1 means all zombies will be zombie bosses (1 out of 1)

Try something like 5...this means 1 in 5 zombies will be a boss.
