### ISSUE TITLE
GameStages config not there

### ISSUE THREAD

**Issue by rosethenoob** [p1ut0nium-git/Rough-Mobs-Revamped#58]
I have the Game Stages mod and the Rough Mobs Revamped both installed, but I don't even see the Game Stages config section anywhere.

[Config](https://hastebin.com/raw/ecosopufif)

Mods Installed:
![Mods](https://user-images.githubusercontent.com/37458083/97852920-000a3e00-1cbd-11eb-9403-99f586eea6f4.png)

**Comment by p1ut0nium-git** [comment]
It is in the rough mobs revamped config file. Just search for stages. Be sure you update to latest too.

**Comment by ghost** [comment]
I tried to search the text file for any mention of `stage`, but couldn't find any. I installed `roughmobsrevamped-1.12.2-2.3.23.jar` and `GameStages-1.12.2-2.0.123.jar`
