### ISSUE TITLE
[Bug] Zombie and skeleton bosses only spawn if language is en_us

### ISSUE THREAD

**Issue by TCreopargh** [p1ut0nium-git/Rough-Mobs-Revamped#64]
When the language is set to zh_cn, I've played for months and not even a boss spawned, but when I change the language to en_us, bosses immediately began spawning.

**Comment by p1ut0nium-git** [comment]
I added localization support in 2.0.32 . Hopefully that fixes it, but you must create your own language file resource pack. Or create it and give it to me and I will add it.

use this to create one: https://github.com/p1ut0nium-git/Rough-Mobs-Revamped/blob/1.12.2/src/main/resources/assets/roughmobsrevamped/lang/en_us.lang
