### ISSUE TITLE
[BUG] Crash in unknown circumstanes when a mob spawns

### ISSUE THREAD

**Issue by Kevadroz** [p1ut0nium-git/Rough-Mobs-Revamped#73]
**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.26
 - Mod: 0.0.3

**Describe the bug**
When a mob spawns the game may crash.

**To Reproduce**
1. Install unknown combination of mods (see _additional context_)
2. Set time to night (optional)
3. Place down a repeating command block with `kill @e[type=!minecraft:player]` and activate it.
4. See the game crash in no time.

**Expected behavior**
The game does not crash.

**Additional context**
I encountered this problem in my private modpack after installing some mods the other day, as you should be able to see the only info in the crash report is that is entity-spawning related. I tried disabling in multimc some of the mods that may have caused this (specially the ones installed recently) including scaling health (& silent lib), roadrunner, blame! and enhanced celestials… at the end disabling only your mod (blame! was also disabled in my test, but it was added later so i'm not considering it important) prevented the issue from manifesting itself in my latest debugging test, so i'm leaving this report here since this mod appears to be related.

Do you have any idea why this happens or should I keep searching for problematic mods (if anymore else)?

**Crash Report**
[Crashy](https://crashy.net/WgQdgfOXOQpqggGQ2qK5), I was using Not Enough Crashes. (There's a button in the upper right corner for the raw report)

**Comment by p1ut0nium-git** [comment]
Thanks for the report; however according to your crash’s report, RMR doesn’t make an appearance. The only mod that is showing up is Enhanced Celestials. From my own private server experience, EH has had crash problem too.

I can’t debug problems with RMR if there are no reports of it doing anything.

That being said, please also consider this is a very early alpha of RMR.

**Comment by Kevadroz** [comment]
> The only mod that is showing up is Enhanced Celestials

I know, and as i said i disabled that one in a test (and the issue was still there). This is why this took me a bunch of debugging test to find anything.
> That being said, please also consider this is a very early alpha of RMR.

Which is why I tough this one was causing the problem.

Anyways, I probably will debug this more, i'll comment here anything that is related with this mod.
